services:
  - type: web
    name: api-mydata
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL_POOLER
        sync: false
        # Valeur attendue: postgresql://postgres.<ref>:<mot-de-passe>@<pooler>:6543/postgres?sslmode=require
      - key: PORT
        value: 10000
